from datetime import datetime
from html import escape


def generate_html_report(
    target,
    open_tcp,
    open_udp,
    banners,
    cve_map,
    misconfigs,
    output_file,
    os_guess="Unknown",
    ssl_findings=None,
    web_info=None,
    extra_findings=None,
    profile="quick",
):
    print(f"[+] Generating HTML report: {output_file}")
    scanned_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    ssl_findings = ssl_findings or []
    web_info = web_info or {}
    extra_findings = extra_findings or []

    def esc(x):
        return escape(str(x))

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Vulnerability Scan Report - {esc(target)}</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      background: #0b1020;
      color: #f2f2f2;
      margin: 0;
      padding: 20px;
    }}
    .container {{
      max-width: 1100px;
      margin: 0 auto;
      background: #111627;
      border-radius: 12px;
      padding: 20px 30px 40px 30px;
      box-shadow: 0 12px 30px rgba(0,0,0,0.5);
    }}
    h1, h2, h3 {{
      color: #fff;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 25px;
    }}
    th, td {{
      border-bottom: 1px solid #333;
      padding: 8px;
      text-align: left;
      font-size: 14px;
    }}
    th {{
      background: #1a2135;
    }}
    ul {{
      font-size: 14px;
    }}
    .tag {{
      display: inline-block;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 11px;
      margin-right: 4px;
    }}
    .tag-issue {{
      background: #c62828;
    }}
    .cve-score {{
      font-weight: bold;
      color: #ffb300;
    }}
    .footer {{
      margin-top: 25px;
      font-size: 12px;
      color: #aaaaaa;
    }}
  </style>
</head>
<body>
  <div class="container">
    <h1>Vulnerability Scan Report</h1>
    <p><strong>Target:</strong> {esc(target)}<br>
       <strong>Profile:</strong> {esc(profile.upper())}<br>
       <strong>Guessed OS:</strong> {esc(os_guess)}<br>
       <strong>Scanned at:</strong> {esc(scanned_at)}</p>

    <h2>Open TCP Ports</h2>
    <p>{len(open_tcp)} port(s) open.</p>
    <table>
      <tr><th>Port</th><th>Banner</th></tr>"""

    for p in sorted(open_tcp):
        banner = banners.get(p, "")
        html += f"<tr><td>{p}</td><td>{esc(banner)}</td></tr>"

    html += """
    </table>

    <h2>Open/Filtered UDP Ports</h2>
    <p>{udp_count} port(s) open or filtered.</p>
    <table>
      <tr><th>Port</th></tr>""".format(udp_count=len(open_udp))

    for p in sorted(open_udp):
        html += f"<tr><td>{p}</td></tr>"

    html += """
    </table>

    <h2>Detected Misconfigurations / Risky Findings</h2>
    <ul>"""

    if misconfigs:
        for issue in misconfigs:
            html += f"<li><span class='tag tag-issue'>ISSUE</span> {esc(issue)}</li>"
    else:
        html += "<li>No obvious misconfigurations detected with current rules.</li>"

    html += """
    </ul>

    <h2>Additional Findings (Web / SSL / Heuristics)</h2>
    <ul>"""

    if extra_findings:
        for f in extra_findings:
            html += f"<li>{esc(f)}</li>"
    else:
        html += "<li>No additional findings reported.</li>"

    html += """
    </ul>

    <h2>Web Application Details</h2>"""

    if not web_info:
        html += "<p>No HTTP/HTTPS services detected or scanned.</p>"
    else:
        html += "<table><tr><th>Port</th><th>Title</th><th>Interesting Paths</th></tr>"
        for port, info in web_info.items():
            title = esc(info.get("title") or "")
            paths = "<br>".join(esc(p) for p in info.get("interesting_paths", []))
            html += f"<tr><td>{port}</td><td>{title}</td><td>{paths}</td></tr>"
        html += "</table>"

    html += """
    <h2>Potential CVEs (based on banners)</h2>"""

    if not cve_map:
        html += "<p>No CVEs were identified from service banners.</p>"
    else:
        for port, cves in cve_map.items():
            html += f"<h3>Port {port}</h3>"
            if not cves:
                html += "<p>No CVEs found.</p>"
                continue
            html += "<table><tr><th>CVE ID</th><th>Score</th><th>Description</th></tr>"
            for cve in cves:
                score = cve.get("score", "-")
                html += (
                    f"<tr><td>{esc(cve['id'])}</td>"
                    f"<td class='cve-score'>{esc(score)}</td>"
                    f"<td>{esc(cve['description'])}</td></tr>"
                )
            html += "</table>"

    html += """
    <div class="footer">
      <p>This report was generated by a custom Python vulnerability scanner.</p>
    </div>
  </div>
</body>
</html>
"""
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html)
